### PR TITLE
Migrate remaining classes to Jackson

### PR DESCRIPTION
**Pull request by walterdeboer**
### Additional Details

- The optString didn't work as expected, returning "null" instead of null

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Review by nscuro — APPROVED** [review]

**Comment by nscuro** [comment]
@walterdeboer Ready to merge? PR is still in draft. :p

**Comment by walterdeboer** [comment]
@nscuro  Still fixing some tests... Won't be long now

**Comment by walterdeboer** [comment]
Tests are still running, but I think this is it...

**Comment by walterdeboer** [comment]
You might want to check the last commits. the optString didn't work as expected, returning "null" instead of null

**Comment by walterdeboer** [comment]
Tests run: 1061, Failures: 0, Errors: 0, Skipped: 1

**Pull request merged**
